name: "trufflehog"

on:
  push:
    branches:
      - "v2"
  pull_request:

jobs:
  scan:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "trufflesecurity/trufflehog@b78fbfd8eb982f4802e09a265fb2bc37b3040975" # main
        with:
          extra_args: "--results=verified,unknown"
